version: "3"

volumes:
  mysql:
  project:
  results:

services:
  mysql:
    build: images/mysql
    network_mode: bridge
    volumes:
     - "mysql:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  makeproject:
    build: images/makeproject
    hostname: boincserver
    network_mode: bridge
    links: 
     - mysql
    volumes:
     - "project:/root/project.dst"
    environment:
     - URL_BASE=$URL_BASE
     - PROJECT=$PROJECT

  apache:
    build: images/apache
    hostname: $PROJECT
    network_mode: bridge
    links:
     - mysql
    volumes: 
     - "project:/root/project"
     - "results:/results"
     - "/var/run/docker.sock:/var/run/docker.sock"
    ports: 
     - "80:80"
    tty: true
    environment:
     - URL_BASE=$URL_BASE
     - PROJECT=$PROJECT
